version: '3.7'
networks:
  traefik:
  db:

services:
  traefik:
    image: traefik:latest
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
 #     - "8090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yaml:/traefik.yaml"
      - "./acme:/acme"
    labels:
      - "traefik.docker.network=wordpress_docker_stack_traefik"
